// Advanced Vector Generator with High-Quality Output
class VectorGenerator {
  constructor() {
    this.qualitySettings = {
      high: { resolution: 4096, detail: 100, format: 'svg' },
      medium: { resolution: 2048, detail: 80, format: 'svg' },
      low: { resolution: 1024, detail: 60, format: 'svg' }
    };
  }
  
  generateLogo(settings) {
    return new Promise((resolve) => {
      // Simulate AI processing
      setTimeout(() => {
        const logo = this.createLogoSVG(settings);
        resolve(logo);
      }, 2000);
    });
  }
  
  createLogoSVG(settings) {
    const { name, style, colors, quality } = settings;
    const qualityLevel = this.qualitySettings[quality || 'high'];
    
    return `
<svg width="${qualityLevel.resolution}" height="${qualityLevel.resolution}" viewBox="0 0 500 500" xmlns="http://www.w3.org/2000/svg">
  <defs>
    <linearGradient id="grad1" x1="0%" y1="0%" x2="100%" y2="100%">
      <stop offset="0%" style="stop-color:${colors.primary};stop-opacity:1" />
      <stop offset="100%" style="stop-color:${colors.secondary};stop-opacity:1" />
    </linearGradient>
    
    <filter id="shadow" x="-20%" y="-20%" width="140%" height="140%">
      <feGaussianBlur in="SourceAlpha" stdDeviation="10"/>
      <feOffset dx="5" dy="5" result="offsetblur"/>
      <feComponentTransfer>
        <feFuncA type="linear" slope="0.3"/>
      </feComponentTransfer>
      <feMerge> 
        <feMergeNode/>
        <feMergeNode in="SourceGraphic"/> 
      </feMerge>
    </filter>
    
    <pattern id="grid" width="50" height="50" patternUnits="userSpaceOnUse">
      <path d="M 50 0 L 0 0 0 50" fill="none" stroke="white" stroke-width="1" opacity="0.1"/>
    </pattern>
  </defs>
  
  <!-- Background -->
  <rect width="500" height="500" rx="50" fill="url(#grad1)"/>
  
  <!-- Main Shape -->
  <g transform="translate(150, 150)" filter="url(#shadow)">
    ${this.getShapeByStyle(style, colors)}
  </g>
  
  <!-- Company Name -->
  <text x="250" y="420" text-anchor="middle" font-family="Arial, sans-serif" font-size="40" font-weight="bold" fill="white">
    ${name}
  </text>
  
  <!-- Watermark -->
  <text x="480" y="490" text-anchor="end" font-family="Arial" font-size="12" fill="rgba(255,255,255,0.3)">
    Generated by DesignBrief AI
  </text>
</svg>
    `;
  }
  
  getShapeByStyle(style, colors) {
    const shapes = {
      modern: `
        <circle cx="100" cy="100" r="80" fill="${colors.accent}" opacity="0.8"/>
        <rect x="40" y="40" width="120" height="120" rx="20" fill="white" opacity="0.9"/>
        <polygon points="100,30 170,100 100,170 30,100" fill="${colors.primary}" opacity="0.7"/>
      `,
      minimalist: `
        <circle cx="100" cy="100" r="60" fill="none" stroke="white" stroke-width="8"/>
        <line x1="100" y1="40" x2="100" y2="160" stroke="white" stroke-width="8"/>
        <line x1="40" y1="100" x2="160" y2="100" stroke="white" stroke-width="8"/>
      `,
      geometric: `
        <polygon points="100,30 170,100 100,170 30,100" fill="${colors.primary}" opacity="0.8"/>
        <circle cx="100" cy="100" r="40" fill="${colors.secondary}" opacity="0.6"/>
        <rect x="70" y="70" width="60" height="60" rx="10" fill="white" opacity="0.7"/>
      `,
      organic: `
        <path d="M100,50 C150,30 180,80 170,130 C160,180 120,190 80,170 C40,150 20,100 40,60 C60,20 100,10 140,30" 
              fill="${colors.primary}" opacity="0.7"/>
        <circle cx="100" cy="100" r="30" fill="${colors.accent}" opacity="0.8"/>
      `
    };
    
    return shapes[style] || shapes.modern;
  }
  
  generateUIComponents(settings) {
    return {
      buttons: this.generateButtonSystem(settings),
      cards: this.generateCardSystem(settings),
      forms: this.generateFormElements(settings),
      icons: this.generateIconSet(settings)
    };
  }
  
  generateButtonSystem(settings) {
    return `
<svg width="800" height="400" viewBox="0 0 800 400" xmlns="http://www.w3.org/2000/svg">
  <!-- Primary Button -->
  <rect x="50" y="50" width="200" height="60" rx="12" fill="${settings.colors.primary}"/>
  <text x="150" y="85" text-anchor="middle" font-family="Inter" font-size="18" font-weight="600" fill="white">
    Primary Button
  </text>
  
  <!-- Secondary Button -->
  <rect x="50" y="150" width="200" height="60" rx="12" fill="transparent" stroke="${settings.colors.primary}" stroke-width="2"/>
  <text x="150" y="185" text-anchor="middle" font-family="Inter" font-size="18" font-weight="600" fill="${settings.colors.primary}">
    Secondary Button
  </text>
  
  <!-- Ghost Button -->
  <rect x="50" y="250" width="200" height="60" rx="12" fill="rgba(99, 102, 241, 0.1)"/>
  <text x="150" y="285" text-anchor="middle" font-family="Inter" font-size="18" font-weight="600" fill="${settings.colors.primary}">
    Ghost Button
  </text>
</svg>
    `;
  }
}

// Initialize generator
const vectorGenerator = new VectorGenerator();

// Enhanced Generate Function
async function generateHighQualityAssets() {
  if (!userManager.currentUser) {
    showToast('Please sign up to generate assets', 'error');
    showSignupModal();
    return;
  }
  
  const brief = document.getElementById('textBrief').value;
  if (!brief.trim()) {
    showToast('Please enter a design brief', 'error');
    return;
  }
  
  // Show loading
  const generateBtn = document.getElementById('generateBtn');
  generateBtn.innerHTML = '<i class="fas fa-spinner fa-spin mr-3"></i> Generating High-Quality Assets...';
  generateBtn.disabled = true;
  
  // Extract settings from brief
  const settings = analyzeBrief(brief);
  
  try {
    // Generate logo
    const logo = await vectorGenerator.generateLogo({
      name: settings.companyName || 'Your Brand',
      style: settings.style || 'modern',
      colors: {
        primary: document.getElementById('primaryColor').value,
        secondary: '#8b5cf6',
        accent: '#10b981'
      },
      quality: 'high'
    });
    
    // Generate UI components
    const uiComponents = vectorGenerator.generateUIComponents({
      colors: {
        primary: document.getElementById('primaryColor').value
      }
    });
    
    // Save to user account
    userManager.saveAsset({
      type: 'logo',
      content: logo,
      settings: settings,
      format: 'svg',
      size: '4096x4096'
    });
    
    userManager.trackGeneration();
    
    // Update preview
    document.getElementById('previewCanvas').innerHTML = `
      <div class="w-full">
        <div class="mb-6">
          <div class="text-lg font-bold mb-2">High-Quality Logo Generated</div>
          <div class="bg-gray-800 rounded-lg p-4">
            ${logo}
          </div>
        </div>
        
        <div class="grid grid-cols-2 gap-4">
          <div class="bg-gray-900 rounded-lg p-4">
            <div class="text-sm text-gray-400 mb-2">Button System</div>
            ${uiComponents.buttons}
          </div>
          <div class="bg-gray-900 rounded-lg p-4">
            <div class="text-sm text-gray-400 mb-2">Card Components</div>
            <div class="bg-gray-800 rounded-lg p-3">
              <div class="font-medium mb-1">Design Complete</div>
              <div class="text-gray-400 text-sm">All files ready for download</div>
            </div>
          </div>
        </div>
      </div>
    `;
    
    // Enable download
    window.generatedAssets = {
      logo: logo,
      uiComponents: uiComponents,
      settings: settings
    };
    
    // Show success
    showToast('🎨 High-quality vector assets generated!', 'success');
    
    // Update user stats
    userManager.showDashboard();
    
  } catch (error) {
    showToast('Error generating assets', 'error');
    console.error(error);
  } finally {
    generateBtn.innerHTML = '<i class="fas fa-bolt mr-3"></i> Generate Complete Design Files';
    generateBtn.disabled = false;
  }
}

function analyzeBrief(brief) {
  // Simple AI analysis
  const settings = {
    style: 'modern',
    colors: ['#6366F1', '#8B5CF6'],
    companyName: extractCompanyName(brief)
  };
  
  if (brief.toLowerCase().includes('minimal')) settings.style = 'minimalist';
  if (brief.toLowerCase().includes('geometric')) settings.style = 'geometric';
  if (brief.toLowerCase().includes('organic')) settings.style = 'organic';
  
  // Extract colors from brief
  const colorMatches = brief.match(/#[0-9A-Fa-f]{6}|rgb\([^)]+\)/g);
  if (colorMatches) {
    settings.colors = colorMatches.slice(0, 3);
  }
  
  return settings;
}

function extractCompanyName(text) {
  const nameMatch = text.match(/"([^"]+)"/);
  if (nameMatch) return nameMatch[1];
  
  const words = text.split(' ');
  for (let i = 0; i < words.length; i++) {
    if (words[i].toLowerCase() === 'company' && words[i + 1]) {
      return words[i + 1];
    }
  }
  
  return 'Your Brand';
}